### ISSUE TITLE
Prereqs not getting installed

### ISSUE THREAD

**Issue by ugexe** [garfieldnate/Algorithm-AM#25]
'perl Makefile.PL && make' or 'dzil build' does not install prereqs (like Text::Table, Crypt::PRNG, Exporter::Easy, Test::LongString)

After forking the project I had to manually install these, even though for instance Text::Table is in the Makefile.

**Comment by garfieldnate** [comment]
dist.ini has been redone with my personal plugin bundle (which still has problems, but not this one, I don't think).
